# Autogenerated port exports.
export LATTICE_PORT_INPUT='examples/board/state/input.fifo'
export LATTICE_PORT_INPUT_TYPE='fifo'
export LATTICE_PORT_OUTPUT='examples/board/state/output.fifo'
export LATTICE_PORT_OUTPUT_TYPE='fifo'
