# Autogenerated. Source this file in your shell.
export LATTICE_BOARD='/home/main/github/lattice-netcat/examples/board-netcat'
export LATTICE_NODE_ID='netcat-demo'
export LATTICE_SOCKET_DIR='state/sockets'
