# Autogenerated. Source this file in your shell.
export LATTICE_BOARD='/home/main/devops/port-lattice/runtime/examples/simple-board'
export LATTICE_NODE_ID='local'
export LATTICE_SOCKET_DIR='state/sockets'
