# Autogenerated port exports.
export LATTICE_PORT_INPUT='/home/main/devops/port-lattice/runtime/examples/simple-board/state/sockets/input.fifo'
export LATTICE_PORT_INPUT_DIRECTION='in'
export LATTICE_PORT_INPUT_IN='/home/main/devops/port-lattice/runtime/examples/simple-board/state/sockets/input.fifo'
export LATTICE_PORT_OUTPUT='/home/main/devops/port-lattice/runtime/examples/simple-board/state/sockets/output.fifo'
export LATTICE_PORT_OUTPUT_DIRECTION='out'
export LATTICE_PORT_OUTPUT_OUT='/home/main/devops/port-lattice/runtime/examples/simple-board/state/sockets/output.fifo'
