# Autogenerated. Source this file in your shell.
export LATTICE_BOARD='/home/main/devops/port-lattice/runtime/examples/protocol-matrix'
export LATTICE_NODE_ID='protocol-matrix'
export LATTICE_SOCKET_DIR='state/sockets'
